# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Thêm dòng này để cấu hình token tải xuống Mapbox SDK
ENV['MAPBOX_DOWNLOADS_TOKEN'] = 'sk.eyJ1IjoibW9ubHljdXRlIiwiYSI6ImNtMDI4enByaDAwMnIycXIwdDhqc3diNHgifQ.cpA69qDo8WHZ7ZxeGzCSlw'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Thêm dòng này để chỉ định phiên bản Mapbox-iOS-SDK
  pod 'Mapbox-iOS-SDK', '~> 6.4.1'
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      
      # Thêm cài đặt này để loại bỏ arm64 cho simulator
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
  
  # Fix cho Xcode 15
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'PERMISSION_EVENTS=1',
          'PERMISSION_REMINDERS=1',
          'PERMISSION_CONTACTS=1',
          'PERMISSION_CAMERA=1',
          'PERMISSION_MICROPHONE=1',
          'PERMISSION_SPEECH_RECOGNIZER=1',
          'PERMISSION_PHOTOS=1',
          'PERMISSION_NOTIFICATIONS=1',
          'PERMISSION_MEDIA_LIBRARY=1',
          'PERMISSION_SENSORS=1',
          'PERMISSION_BLUETOOTH=1',
          'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
          'PERMISSION_CRITICAL_ALERTS=1'
        ]
      end
    end
  end
end